"""
GitHub Agent — READ-ONLY
Fetches commit history from all repositories in a GitHub organization.
NEVER writes, pushes, creates, deletes, or modifies any repository content.
Only uses GET endpoints (list repos, list commits).
"""

import logging
import re
from github import Github, GithubException
from models import CommitInfo
import config

logger = logging.getLogger("agent.github")

# Commit messages to skip — these don't represent meaningful work
SKIP_PATTERNS = [
    # Merge commits
    re.compile(r"^Merge (branch|pull request|remote-tracking)", re.IGNORECASE),
    # Version bumps / auto-generated
    re.compile(r"^(bump|release|v?\d+\.\d+)", re.IGNORECASE),
    # Trivial / noise commits
    re.compile(r"^(initial commit|first commit|init|wip|tmp|test commit)$", re.IGNORECASE),
    # Auto-generated by tools
    re.compile(r"^(auto-commit|automated|generated)", re.IGNORECASE),
    # Just a dot or single char
    re.compile(r"^.{0,3}$"),
]

# Bot author detection — only exact username matches or the [bot] suffix.
# Using exact matches prevents false positives on real users whose names
# might contain substrings like "bot" or "renovate".
BOT_EXACT_USERNAMES = {"dependabot", "renovate-bot", "github-actions", "snyk-bot", "codecov-commenter", "codecov-io"}
BOT_SUFFIX = "[bot]"

# Repos with these name patterns are likely not code repos
SKIP_REPO_PATTERNS = re.compile(r"(\.github|template|archived|deprecated)", re.IGNORECASE)

# Safety cap: max commits to process per repo per poll cycle.
# Prevents runaway iteration when last_sha is missing from history (force push / rebase).
MAX_NEW_COMMITS_PER_REPO = 100


class GitHubAgent:
    """
    Read-only agent that fetches commits from all org repos.
    Uses ONLY read endpoints: org.get_repos() and repo.get_commits().
    """

    def __init__(self, token: str, org_name: str):
        self._gh = Github(token, per_page=30)  # limit page size to reduce API calls
        self._org_name = org_name
        logger.info(f"GitHubAgent initialized for org: {org_name} (read-only)")

    def fetch_org_repos(self) -> list:
        """List all non-archived, non-fork, non-empty repositories in the org."""
        try:
            org = self._gh.get_organization(self._org_name)
            repos = []
            skipped_repos = []
            for repo in org.get_repos(type="all"):
                if repo.archived or repo.fork:
                    continue
                # Skip repos with known non-code patterns
                if SKIP_REPO_PATTERNS.search(repo.name):
                    skipped_repos.append(f"{repo.full_name} (name pattern)")
                    continue
                # Skip empty repos (size == 0 means no content pushed)
                if repo.size == 0:
                    skipped_repos.append(f"{repo.full_name} (empty)")
                    continue
                repos.append(repo)
            if skipped_repos:
                logger.info(f"REPOS_SKIPPED | {len(skipped_repos)} repo(s): {', '.join(skipped_repos)}")
            logger.info(f"Found {len(repos)} active repos in {self._org_name}")
            return repos
        except GithubException as e:
            logger.error(f"Failed to fetch org repos: {e}")
            return []

    def fetch_repo_branches(self, repo) -> list[str]:
        """List all branch names for a repo. Returns at least the default branch."""
        try:
            branches = [b.name for b in repo.get_branches()]
            if not branches:
                branches = [repo.default_branch]
            logger.debug(f"BRANCHES | {repo.full_name}: {len(branches)} branch(es)")
            return branches
        except GithubException as e:
            logger.debug(f"Could not list branches for {repo.full_name}: {e}")
            return [repo.default_branch]

    def fetch_new_commits(
        self, repo, branch: str, last_sha: str | None, seen_shas: set[str] | None = None
    ) -> tuple[list[CommitInfo], str | None, int]:
        """
        Fetch new commits from a specific branch since last_sha.
        seen_shas: set of SHAs already processed in this scan cycle (cross-branch dedup).
        Returns (list_of_commits_oldest_first, latest_sha, total_found_count).
        total_found_count includes skipped commits (for diagnostics).
        """
        if seen_shas is None:
            seen_shas = set()
        try:
            commits_page = repo.get_commits(sha=branch)

            new_commits = []
            latest_sha = None
            total_found = 0
            skipped_count = 0

            for commit in commits_page:
                sha = commit.sha

                # Set the latest SHA from the first (newest) commit
                if latest_sha is None:
                    latest_sha = sha

                # Stop when we reach the last processed commit
                if sha == last_sha:
                    if total_found == 0:
                        log_fn = logger.info if config.VERBOSE_REPO_SCAN else logger.debug
                        log_fn(
                            f"REPO_UNCHANGED | {repo.full_name} | branch={branch} | "
                            f"head={sha[:8]} — no new commits"
                        )
                    break

                # If no last_sha (first run), just record position — don't backfill
                if last_sha is None:
                    logger.info(
                        f"FIRST_RUN | {repo.full_name} | Recording position at {sha[:8]} "
                        f"(branch: {branch}) — no backfill"
                    )
                    latest_sha = sha
                    break

                # Cross-branch dedup: skip if already processed from another branch
                if sha in seen_shas:
                    continue

                total_found += 1

                # Safety cap: stop if too many commits (e.g. last_sha lost after force push)
                if total_found > MAX_NEW_COMMITS_PER_REPO:
                    logger.warning(
                        f"COMMIT_CAP_HIT | {repo.full_name}:{branch} | "
                        f"Stopped at {MAX_NEW_COMMITS_PER_REPO} commits. "
                        f"Possible force-push or stale SHA. Some older commits may be missed."
                    )
                    break

                msg_first_line = commit.commit.message.strip().splitlines()[0][:80]
                author = commit.author.login if commit.author else (commit.commit.author.name if commit.commit.author else "unknown")

                skip_reason = self._get_skip_reason(commit)
                if skip_reason:
                    skipped_count += 1
                    logger.info(
                        f"COMMIT_SKIPPED | repo={repo.full_name} | branch={branch} | sha={sha[:8]} | "
                        f"author={author} | reason={skip_reason} | \"{msg_first_line}\""
                    )
                    seen_shas.add(sha)
                    continue

                info = self._to_commit_info(commit, repo, branch)
                logger.info(
                    f"COMMIT_FOUND | repo={repo.full_name} | branch={branch} | sha={sha[:8]} | "
                    f"author={author} | files={info.files_changed} | "
                    f"lines={info.lines_changed} | \"{msg_first_line}\""
                )
                seen_shas.add(sha)
                new_commits.append(info)

            # Return oldest-first order
            new_commits.reverse()

            if total_found > 0:
                logger.info(
                    f"{repo.full_name}: {total_found} new commit(s) found — "
                    f"{len(new_commits)} accepted, {skipped_count} skipped"
                )
            return new_commits, latest_sha or last_sha, total_found

        except GithubException as e:
            status = getattr(e, 'status', None)
            # 409 = empty repo, 404 = deleted/private, 403 = no access
            if status in (409, 404, 403):
                logger.debug(f"Skipping {repo.full_name}: {status} {e.data.get('message', '')}")
            else:
                logger.error(f"Failed to fetch commits for {repo.full_name}: {e}")
            return [], last_sha, 0
        except Exception as e:
            logger.error(f"Unexpected error fetching {repo.full_name}: {e}")
            return [], last_sha, 0

    def fetch_all_org_commits(
        self, repo_shas: dict[str, str]
    ) -> tuple[list[CommitInfo], dict[str, str]]:
        """
        Iterate all org repos and ALL branches, fetch new commits for each.
        repo_shas key format: "org/repo:branch" (e.g. "latelogic/app:main").
        Returns (aggregated_commits, updated_sha_map).
        """
        repos = self.fetch_org_repos()
        all_commits = []
        updated_shas = {}
        total_found_all = 0
        total_skipped_all = 0
        branches_with_commits = 0
        first_run_branches = 0
        unchanged_branches = 0
        total_branches = 0
        sha_changed = []

        for repo in repos:
            branches = self.fetch_repo_branches(repo)
            # Cross-branch dedup: commits shared between branches are only processed once
            seen_shas_for_repo = set()

            for branch in branches:
                total_branches += 1
                sha_key = f"{repo.full_name}:{branch}"
                last_sha = repo_shas.get(sha_key)

                # Migration: check old format (repo-only key) for the default branch
                if last_sha is None and branch == repo.default_branch:
                    last_sha = repo_shas.get(repo.full_name)
                    if last_sha:
                        logger.info(
                            f"SHA_MIGRATE | {repo.full_name} → {sha_key} "
                            f"(migrating from repo-only key)"
                        )

                if last_sha is None:
                    first_run_branches += 1

                new_commits, latest_sha, found_count = self.fetch_new_commits(
                    repo, branch, last_sha, seen_shas_for_repo
                )

                total_found_all += found_count
                total_skipped_all += found_count - len(new_commits)
                if found_count > 0:
                    branches_with_commits += 1

                if latest_sha:
                    updated_shas[sha_key] = latest_sha

                # Track SHA changes for diagnostics
                if last_sha and latest_sha and last_sha == latest_sha:
                    unchanged_branches += 1
                elif last_sha and latest_sha and last_sha != latest_sha:
                    sha_changed.append(f"{repo.full_name}:{branch}")

                all_commits.extend(new_commits)

        # Always log scan summary
        logger.info(
            f"SCAN_COMPLETE | repos={len(repos)} | branches={total_branches} | "
            f"branches_with_new_commits={branches_with_commits} | "
            f"total_found={total_found_all} | accepted={len(all_commits)} | "
            f"skipped={total_skipped_all} | first_run={first_run_branches} | "
            f"unchanged={unchanged_branches}"
        )
        if sha_changed:
            logger.info(f"SHA_CHANGED | {', '.join(sha_changed)}")

        return all_commits, updated_shas

    def fetch_commit_author(self, sha: str) -> str | None:
        """
        Look up the author of a commit by SHA across the org.
        Uses GitHub search API to find the commit without knowing the repo.
        Returns the GitHub username or None.
        """
        try:
            commits = self._gh.search_commits(query=f"hash:{sha} org:{self._org_name}")
            for commit in commits:
                if commit.author:
                    return commit.author.login
                elif commit.commit and commit.commit.author:
                    return commit.commit.author.name
            return None
        except GithubException as e:
            logger.debug(f"Could not look up commit {sha[:8]}: {e}")
            return None
        except Exception as e:
            logger.debug(f"Commit lookup failed for {sha[:8]}: {e}")
            return None

    def audit_missed_commits(
        self, repo_shas: dict[str, str], known_shas: set[str], lookback: int = 20
    ) -> list[CommitInfo]:
        """
        Integrity check: for each repo+branch, fetch the last `lookback` commits
        and compare against known_shas (all SHAs we've ever processed or buffered).
        Any commit between HEAD and our recorded last_sha that isn't in known_shas
        AND wasn't skipped is a missed commit.

        Returns list of missed CommitInfo objects that should be re-injected.
        """
        repos = self.fetch_org_repos()
        missed = []
        audit_seen = set()  # Dedup across branches

        for repo in repos:
            branches = self.fetch_repo_branches(repo)

            for branch in branches:
                sha_key = f"{repo.full_name}:{branch}"
                last_sha = repo_shas.get(sha_key)
                # Migration fallback for default branch
                if not last_sha and branch == repo.default_branch:
                    last_sha = repo_shas.get(repo.full_name)
                if not last_sha:
                    continue  # First-run branches handled by normal flow

                try:
                    commits_page = repo.get_commits(sha=branch)
                    count = 0

                    for commit in commits_page:
                        sha = commit.sha
                        count += 1

                        if count > lookback:
                            break
                        if sha == last_sha:
                            break

                        if sha in known_shas or sha in audit_seen:
                            continue

                        if self._get_skip_reason(commit):
                            continue

                        info = self._to_commit_info(commit, repo, branch)
                        logger.warning(
                            f"MISSED_COMMIT | repo={repo.full_name} | branch={branch} | "
                            f"sha={sha[:8]} | author={info.author} | "
                            f"files={info.files_changed} | "
                            f"\"{info.message.splitlines()[0][:80]}\""
                        )
                        audit_seen.add(sha)
                        missed.append(info)

                except GithubException as e:
                    status = getattr(e, 'status', None)
                    if status not in (409, 404, 403):
                        logger.error(f"AUDIT_ERROR | {repo.full_name}:{branch}: {e}")
                except Exception as e:
                    logger.error(f"AUDIT_ERROR | {repo.full_name}:{branch}: {e}")

        if missed:
            logger.warning(f"AUDIT_RESULT | Found {len(missed)} missed commit(s) across org")
        else:
            logger.info("AUDIT_RESULT | No missed commits detected")

        missed.reverse()
        return missed

    def _to_commit_info(self, commit, repo, branch: str) -> CommitInfo:
        author_name = "unknown"
        if commit.author:
            author_name = commit.author.login
        elif commit.commit.author:
            author_name = commit.commit.author.name

        # Fetch file/line stats (triggers one extra API call per commit)
        files_changed = 0
        lines_changed = 0
        try:
            stats = commit.stats
            if stats:
                lines_changed = (stats.additions or 0) + (stats.deletions or 0)
            files = commit.files
            if files:
                files_changed = len(files)
        except Exception as e:
            logger.debug(f"Could not fetch stats for {commit.sha[:8]}: {e}")

        return CommitInfo(
            sha=commit.sha,
            message=commit.commit.message.strip(),
            author=author_name,
            repo=repo.full_name,
            branch=branch,
            timestamp=commit.commit.author.date.isoformat(),
            files_changed=files_changed,
            lines_changed=lines_changed,
        )

    def _get_skip_reason(self, commit) -> str | None:
        """Return skip reason if commit should be filtered, or None if it should be kept."""
        msg = commit.commit.message.strip()

        if not msg:
            return "empty_message"

        for pattern in SKIP_PATTERNS:
            if pattern.search(msg):
                return f"pattern:{pattern.pattern[:30]}"

        author = ""
        if commit.author:
            author = commit.author.login.lower()
        elif commit.commit.author:
            author = commit.commit.author.name.lower()

        if author.endswith(BOT_SUFFIX):
            return f"bot_author:{author}"
        if author in BOT_EXACT_USERNAMES:
            return f"bot_author:{author}"

        return None

    def _should_skip(self, commit) -> bool:
        """Filter out trivial commits that shouldn't become Linear tasks."""
        return self._get_skip_reason(commit) is not None
