"""
GitHub Agent — READ-ONLY
Fetches commit history from all repositories in a GitHub organization.
NEVER writes, pushes, creates, deletes, or modifies any repository content.
Only uses GET endpoints (list repos, list commits).
"""

import logging
import re
from github import Github, GithubException
from models import CommitInfo

logger = logging.getLogger("agent.github")

# Commit messages to skip — these don't represent meaningful work
SKIP_PATTERNS = [
    # Merge commits
    re.compile(r"^Merge (branch|pull request|remote-tracking)", re.IGNORECASE),
    # Version bumps / auto-generated
    re.compile(r"^(bump|release|v?\d+\.\d+)", re.IGNORECASE),
    # Trivial / noise commits
    re.compile(r"^(initial commit|first commit|init|wip|tmp|test commit)$", re.IGNORECASE),
    # Auto-generated by tools
    re.compile(r"^(auto-commit|automated|generated)", re.IGNORECASE),
    # Just a dot or single char
    re.compile(r"^.{0,3}$"),
]

BOT_MARKERS = ("[bot]", "dependabot", "renovate", "github-actions", "snyk-bot", "codecov")

# Repos with these name patterns are likely not code repos
SKIP_REPO_PATTERNS = re.compile(r"(\.github|template|archived|deprecated)", re.IGNORECASE)


class GitHubAgent:
    """
    Read-only agent that fetches commits from all org repos.
    Uses ONLY read endpoints: org.get_repos() and repo.get_commits().
    """

    def __init__(self, token: str, org_name: str):
        self._gh = Github(token, per_page=30)  # limit page size to reduce API calls
        self._org_name = org_name
        logger.info(f"GitHubAgent initialized for org: {org_name} (read-only)")

    def fetch_org_repos(self) -> list:
        """List all non-archived, non-fork, non-empty repositories in the org."""
        try:
            org = self._gh.get_organization(self._org_name)
            repos = []
            for repo in org.get_repos(type="all"):
                if repo.archived or repo.fork:
                    continue
                # Skip repos with known non-code patterns
                if SKIP_REPO_PATTERNS.search(repo.name):
                    logger.debug(f"Skipping repo (name pattern): {repo.full_name}")
                    continue
                # Skip empty repos (size == 0 means no content pushed)
                if repo.size == 0:
                    logger.debug(f"Skipping empty repo: {repo.full_name}")
                    continue
                repos.append(repo)
            logger.info(f"Found {len(repos)} active repos in {self._org_name}")
            return repos
        except GithubException as e:
            logger.error(f"Failed to fetch org repos: {e}")
            return []

    def fetch_new_commits(self, repo, last_sha: str | None) -> tuple[list[CommitInfo], str | None, int]:
        """
        Fetch new commits from a repo's default branch since last_sha.
        Returns (list_of_commits_oldest_first, latest_sha, total_found_count).
        total_found_count includes skipped commits (for diagnostics).
        """
        try:
            branch = repo.default_branch
            commits_page = repo.get_commits(sha=branch)

            new_commits = []
            latest_sha = None
            total_found = 0
            skipped_count = 0

            for commit in commits_page:
                sha = commit.sha

                # Set the latest SHA from the first (newest) commit
                if latest_sha is None:
                    latest_sha = sha

                # Stop when we reach the last processed commit
                if sha == last_sha:
                    break

                # If no last_sha (first run), just record position — don't backfill
                if last_sha is None:
                    logger.info(
                        f"FIRST_RUN | {repo.full_name} | Recording position at {sha[:8]} "
                        f"(branch: {branch}) — no backfill"
                    )
                    latest_sha = sha
                    break

                total_found += 1
                msg_first_line = commit.commit.message.strip().splitlines()[0][:80]
                author = commit.author.login if commit.author else (commit.commit.author.name if commit.commit.author else "unknown")

                skip_reason = self._get_skip_reason(commit)
                if skip_reason:
                    skipped_count += 1
                    logger.info(
                        f"COMMIT_SKIPPED | repo={repo.full_name} | sha={sha[:8]} | "
                        f"author={author} | reason={skip_reason} | \"{msg_first_line}\""
                    )
                    continue

                logger.info(
                    f"COMMIT_FOUND | repo={repo.full_name} | sha={sha[:8]} | "
                    f"author={author} | \"{msg_first_line}\""
                )
                new_commits.append(self._to_commit_info(commit, repo, branch))

            # Return oldest-first order
            new_commits.reverse()

            if total_found > 0:
                logger.info(
                    f"{repo.full_name}: {total_found} new commit(s) found — "
                    f"{len(new_commits)} accepted, {skipped_count} skipped"
                )
            return new_commits, latest_sha or last_sha, total_found

        except GithubException as e:
            status = getattr(e, 'status', None)
            # 409 = empty repo, 404 = deleted/private, 403 = no access
            if status in (409, 404, 403):
                logger.debug(f"Skipping {repo.full_name}: {status} {e.data.get('message', '')}")
            else:
                logger.error(f"Failed to fetch commits for {repo.full_name}: {e}")
            return [], last_sha, 0
        except Exception as e:
            logger.error(f"Unexpected error fetching {repo.full_name}: {e}")
            return [], last_sha, 0

    def fetch_all_org_commits(
        self, repo_shas: dict[str, str]
    ) -> tuple[list[CommitInfo], dict[str, str]]:
        """
        Iterate all org repos and fetch new commits for each.
        Returns (aggregated_commits, updated_sha_map).
        """
        repos = self.fetch_org_repos()
        all_commits = []
        updated_shas = {}
        total_found_all = 0
        total_skipped_all = 0
        repos_with_commits = 0
        first_run_repos = 0

        for repo in repos:
            last_sha = repo_shas.get(repo.full_name)
            if last_sha is None:
                first_run_repos += 1
            new_commits, latest_sha, found_count = self.fetch_new_commits(repo, last_sha)

            total_found_all += found_count
            total_skipped_all += found_count - len(new_commits)
            if found_count > 0:
                repos_with_commits += 1

            if latest_sha:
                updated_shas[repo.full_name] = latest_sha

            all_commits.extend(new_commits)

        # Always log scan summary
        logger.info(
            f"SCAN_COMPLETE | repos={len(repos)} | repos_with_new_commits={repos_with_commits} | "
            f"total_found={total_found_all} | accepted={len(all_commits)} | "
            f"skipped={total_skipped_all} | first_run_repos={first_run_repos}"
        )

        return all_commits, updated_shas

    def fetch_commit_author(self, sha: str) -> str | None:
        """
        Look up the author of a commit by SHA across the org.
        Uses GitHub search API to find the commit without knowing the repo.
        Returns the GitHub username or None.
        """
        try:
            commits = self._gh.search_commits(query=f"hash:{sha} org:{self._org_name}")
            for commit in commits:
                if commit.author:
                    return commit.author.login
                elif commit.commit and commit.commit.author:
                    return commit.commit.author.name
            return None
        except GithubException as e:
            logger.debug(f"Could not look up commit {sha[:8]}: {e}")
            return None
        except Exception as e:
            logger.debug(f"Commit lookup failed for {sha[:8]}: {e}")
            return None

    def _to_commit_info(self, commit, repo, branch: str) -> CommitInfo:
        author_name = "unknown"
        if commit.author:
            author_name = commit.author.login
        elif commit.commit.author:
            author_name = commit.commit.author.name

        return CommitInfo(
            sha=commit.sha,
            message=commit.commit.message.strip(),
            author=author_name,
            repo=repo.full_name,
            branch=branch,
            timestamp=commit.commit.author.date.isoformat(),
        )

    def _get_skip_reason(self, commit) -> str | None:
        """Return skip reason if commit should be filtered, or None if it should be kept."""
        msg = commit.commit.message.strip()

        if not msg:
            return "empty_message"

        for pattern in SKIP_PATTERNS:
            if pattern.search(msg):
                return f"pattern:{pattern.pattern[:30]}"

        author = ""
        if commit.author:
            author = commit.author.login.lower()
        elif commit.commit.author:
            author = commit.commit.author.name.lower()

        for bot in BOT_MARKERS:
            if bot in author:
                return f"bot_author:{bot}"

        return None

    def _should_skip(self, commit) -> bool:
        """Filter out trivial commits that shouldn't become Linear tasks."""
        return self._get_skip_reason(commit) is not None
